name: Universal Obfuscation Workflow

on:
  # 手动触发（带参数）
  workflow_dispatch:
    inputs:
      obfuscation-level:
        description: '混淆级别 (low/medium/high)'
        required: true
        default: 'low'
      target-branch:
        description: '目标分支'
        required: false
        default: 'main'

  # 自动触发条件集合
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'src/**'  # 仅当src目录有变化时触发

  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main'

  schedule:
    - cron: '0 3 * * 1-5'  # 每周一到五UTC时间3点运行
    
  release:
    types: [published]
    
  repository_dispatch:
    types: [run_obfuscation]

jobs:
  obfuscate:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - name: Dynamic Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ 
          github.event_name == 'workflow_dispatch' && 
          inputs.target-branch || 
          github.ref 
        }}
        fetch-depth: 1
        token: ${{ secrets.GH_TOKEN }}

    # 条件判断模块
    - name: Set Obfuscation Level
      id: set-level
      run: |
        LEVEL="${{ github.event.inputs.obfuscation-level || 'low' }}"
        echo "level=${LEVEL}" >> $GITHUB_OUTPUT

    # 下载模块
    - name: Download Assets
      if: ${{ github.event_name != 'pull_request' }}
      uses: robinraju/release-downloader@v1
      with:
        repository: "bia-pain-bache/BPB-Worker-Panel"
        tag: "latest"
        fileName: "worker.zip"
        token: ${{ secrets.GH_TOKEN }}

    # 混淆核心逻辑
    - name: Obfuscation Engine
      env:
        OB_LEVEL: ${{ steps.set-level.outputs.level }}
      run: |
        # 根据级别切换配置
        case $OB_LEVEL in
          "low")
            FLAGS="--compact --rename-globals"
            ;;
          "medium")
            FLAGS="--control-flow-flattening --dead-code-injection"
            ;;
          "high")
            FLAGS="--debug-protection --self-defending"
            ;;
        esac
        
        find ./worker_files -name "*.js" -exec \
          javascript-obfuscator {} $FLAGS --output {} \;

    # 智能提交模块
    - name: Auto Commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "Obfuscation Bot"
        message: "Auto-obfuscated (${{ github.event_name }} trigger)"
        branch: ${{ inputs.target-branch || 'main' }}
        force: ${{ github.event_name == 'schedule' }}  # 定时任务强制推送
